import 'dart:convert';

/// Static level data for first 50 levels
class LevelsData {
  static const List<Map<String, dynamic>> levels = [
    // Tutorial Levels (1-10) - Very Easy
    {
      'number': 1,
      'moveLimit': 30,
      'targetScore': 300,
      'objective': 'score',
      'gridSize': 6,
      'name': 'First Roll',
    },
    {
      'number': 2,
      'moveLimit': 28,
      'targetScore': 350,
      'objective': 'score',
      'gridSize': 6,
      'name': 'Easy Start',
    },
    {
      'number': 3,
      'moveLimit': 26,
      'targetScore': 400,
      'objective': 'score',
      'gridSize': 6,
      'name': 'Keep Going',
    },
    {
      'number': 4,
      'moveLimit': 25,
      'targetScore': 450,
      'objective': 'score',
      'gridSize': 6,
      'name': 'Practice',
    },
    {
      'number': 5,
      'moveLimit': 24,
      'targetScore': 500,
      'objective': 'score',
      'gridSize': 7,
      'name': 'California Dream',
    },
    {
      'number': 6,
      'moveLimit': 24,
      'targetScore': 550,
      'objective': 'collect',
      'gridSize': 7,
      'collectTarget': {'type': 'salmon', 'count': 10},
      'name': 'Salmon Rush',
    },
    {
      'number': 7,
      'moveLimit': 23,
      'targetScore': 600,
      'objective': 'score',
      'gridSize': 7,
      'name': 'Spicy Tuna',
    },
    {
      'number': 8,
      'moveLimit': 23,
      'targetScore': 650,
      'objective': 'collect',
      'gridSize': 7,
      'collectTarget': {'type': 'tuna', 'count': 12},
      'name': 'Tuna Time',
    },
    {
      'number': 9,
      'moveLimit': 22,
      'targetScore': 700,
      'objective': 'score',
      'gridSize': 7,
      'name': 'Rising Sun',
    },
    {
      'number': 10,
      'moveLimit': 22,
      'targetScore': 750,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Dragon Roll',
    },
    // Easy Levels (11-30)
    {
      'number': 11,
      'moveLimit': 22,
      'targetScore': 800,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Garden Party',
    },
    {
      'number': 12,
      'moveLimit': 22,
      'targetScore': 850,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'shrimp', 'count': 15},
      'name': 'Shrimp Swarm',
    },
    {
      'number': 13,
      'moveLimit': 21,
      'targetScore': 900,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Ocean Breeze',
    },
    {
      'number': 14,
      'moveLimit': 21,
      'targetScore': 950,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'avocado', 'count': 15},
      'name': 'Avocado Wave',
    },
    {
      'number': 15,
      'moveLimit': 21,
      'targetScore': 1000,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Rainbow Garden',
    },
    {
      'number': 16,
      'moveLimit': 20,
      'targetScore': 1050,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'cucumber', 'count': 18},
      'name': 'Cucumber Cool',
    },
    {
      'number': 17,
      'moveLimit': 20,
      'targetScore': 1100,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Moon Light',
    },
    {
      'number': 18,
      'moveLimit': 20,
      'targetScore': 1150,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'cheese', 'count': 12},
      'name': 'Cheese Dreams',
    },
    {
      'number': 19,
      'moveLimit': 20,
      'targetScore': 1200,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Star Power',
    },
    {
      'number': 20,
      'moveLimit': 20,
      'targetScore': 1250,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Galaxy Feast',
    },
    // Medium Levels (21-40)
    {
      'number': 21,
      'moveLimit': 20,
      'targetScore': 1300,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Nebula Night',
    },
    {
      'number': 22,
      'moveLimit': 20,
      'targetScore': 1350,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'tamago', 'count': 20},
      'name': 'Golden Eggs',
    },
    {
      'number': 23,
      'moveLimit': 19,
      'targetScore': 1400,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Solar Flare',
    },
    {
      'number': 24,
      'moveLimit': 19,
      'targetScore': 1450,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'sausage', 'count': 15},
      'name': 'Meat Lover',
    },
    {
      'number': 25,
      'moveLimit': 19,
      'targetScore': 1500,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Comet Course',
    },
    {
      'number': 26,
      'moveLimit': 19,
      'targetScore': 1550,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'salmon', 'count': 25},
      'name': 'Salmon Supreme',
    },
    {
      'number': 27,
      'moveLimit': 18,
      'targetScore': 1600,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Stellar Delight',
    },
    {
      'number': 28,
      'moveLimit': 18,
      'targetScore': 1650,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'tuna', 'count': 25},
      'name': 'Tuna Terror',
    },
    {
      'number': 29,
      'moveLimit': 18,
      'targetScore': 1700,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Lunar Lunch',
    },
    {
      'number': 30,
      'moveLimit': 18,
      'targetScore': 1750,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Milky Way',
    },
    // Harder Levels (31-50)
    {
      'number': 31,
      'moveLimit': 18,
      'targetScore': 1800,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Asteroid Belt',
    },
    {
      'number': 32,
      'moveLimit': 18,
      'targetScore': 1850,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'shrimp', 'count': 30},
      'name': 'Shrimp Storm',
    },
    {
      'number': 33,
      'moveLimit': 17,
      'targetScore': 1900,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Plasma Blast',
    },
    {
      'number': 34,
      'moveLimit': 17,
      'targetScore': 1950,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'avocado', 'count': 25},
      'name': 'Green Machine',
    },
    {
      'number': 35,
      'moveLimit': 17,
      'targetScore': 2000,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Quantum Quest',
    },
    {
      'number': 36,
      'moveLimit': 17,
      'targetScore': 2100,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'cucumber', 'count': 30},
      'name': 'Cucumber Crunch',
    },
    {
      'number': 37,
      'moveLimit': 16,
      'targetScore': 2200,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Black Hole',
    },
    {
      'number': 38,
      'moveLimit': 16,
      'targetScore': 2300,
      'objective': 'collect',
      'gridSize': 8,
      'collectTarget': {'type': 'cheese', 'count': 20},
      'name': 'Cheese Galaxy',
    },
    {
      'number': 39,
      'moveLimit': 16,
      'targetScore': 2400,
      'objective': 'score',
      'gridSize': 8,
      'name': 'Supernova',
    },
    {
      'number': 40,
      'moveLimit': 16,
      'targetScore': 2500,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Big Bang',
    },
    // Challenge Levels (41-50)
    {
      'number': 41,
      'moveLimit': 16,
      'targetScore': 2600,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Dark Matter',
    },
    {
      'number': 42,
      'moveLimit': 15,
      'targetScore': 2700,
      'objective': 'collect',
      'gridSize': 9,
      'collectTarget': {'type': 'tamago', 'count': 30},
      'name': 'Egg Explosion',
    },
    {
      'number': 43,
      'moveLimit': 15,
      'targetScore': 2800,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Time Warp',
    },
    {
      'number': 44,
      'moveLimit': 15,
      'targetScore': 2900,
      'objective': 'collect',
      'gridSize': 9,
      'collectTarget': {'type': 'sausage', 'count': 25},
      'name': 'Sausage Sprint',
    },
    {
      'number': 45,
      'moveLimit': 15,
      'targetScore': 3000,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Warp Drive',
    },
    {
      'number': 46,
      'moveLimit': 15,
      'targetScore': 3100,
      'objective': 'collect',
      'gridSize': 9,
      'collectTarget': {'type': 'salmon', 'count': 35},
      'name': 'Salmon Storm',
    },
    {
      'number': 47,
      'moveLimit': 14,
      'targetScore': 3200,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Hyperspace',
    },
    {
      'number': 48,
      'moveLimit': 14,
      'targetScore': 3300,
      'objective': 'collect',
      'gridSize': 9,
      'collectTarget': {'type': 'tuna', 'count': 35},
      'name': 'Tuna Torrent',
    },
    {
      'number': 49,
      'moveLimit': 14,
      'targetScore': 3400,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Event Horizon',
    },
    {
      'number': 50,
      'moveLimit': 14,
      'targetScore': 3500,
      'objective': 'score',
      'gridSize': 9,
      'name': 'Ultimate Chef',
    },
  ];

  static String getLevelsJson() => jsonEncode(levels);
}